### ISSUE TITLE
請 code review PR

### ISSUE THREAD

**Issue by shazi7804** [104corp/puppet-corp104_karaf#2]
@furfur51752000 @edison0513 @abelyang999 

請 review @genchilu 推的 PR #1 確認有沒有問題，並且在以下回復檢查項目與結果。

大家 review 完後，我會再 review 一次。

**Comment by abelyang999** [comment]
如文件所述,安裝測試一切正常
Notice: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]/returns: executed successfully
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[wait karaf start up complete]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[upgrad cxf]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: webconsole]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: cxf]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: cxf-jaxrs]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: http-whiteboard]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: http]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: cxf-jaxws]
Info: /Stage[main]/Corp104_karaf::Config/Exec[start karaf]: Scheduling refresh of Exec[install karaf feature: aries-blueprint]
Info: /Stage[main]/Corp104_karaf::Service/Service[karaf service]: Unscheduling refresh on Service[karaf service]


root@agent02:~# ps auxwwf|grep karaf
root     26710  0.0  0.0  12944  1012 pts/0    S+   14:48   0:00          \_ grep --color=auto karaf
root     24971  0.0  0.0   4504  1740 ?        S    14:45   0:00 /bin/sh /opt/karaf/bin/karaf server
root     25065 19.3 20.6 2677360 423596 ?      Sl   14:45   0:32  \_ /usr/bin/java -Xms128M -Xmx512M -XX:+UnlockDiagnosticVMOptions -Dcom.sun.management.jmxremote -Djava.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/jre/lib/endorsed:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed:/opt/karaf/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/jre/lib/ext:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/opt/karaf/lib/ext -Dkaraf.instances=/opt/karaf/instances -Dkaraf.home=/opt/karaf -Dkaraf.base=/opt/karaf -Dkaraf.data=/opt/karaf/data -Dkaraf.etc=/opt/karaf/etc -Dkaraf.restart.jvm.supported=true -Djava.io.tmpdir=/opt/karaf/data/tmp -Djava.util.logging.config.file=/opt/karaf/etc/java.util.logging.properties -Dkaraf.startLocalConsole=false -Dkaraf.startRemoteShell=true -classpath /opt/karaf/lib/boot/org.apache karaf.diagnostic.boot-4.2.0.jar:/opt/karaf/lib/boot/org.apache.karaf.jaas.boot-4.2.0.jar:/opt/karaf/lib/boot/org.apache karaf.main-4.2.0.jar:/opt/karaf/lib/boot/org.apache.karaf.specs.activator-4.2.0.jar:/opt/karaf/lib/boot/org.osgi.core-6.0.0.jar org.apache.karaf.main.Main

**Comment by abelyang999** [comment]
補充:
root@agent02:~# systemctl |grep karaf
karaf.service                                                                            loaded active running   karaf

**Comment by shazi7804** [comment]
Hi @abelyang999 

這是 Raw Data，我們不需要 Raw Data 的訊息，這些是當出問題後用來 Debug 使用，我期望的是做 `Code Review`，Code Review 的重點是查看 Puppet code 是否符合邏輯、有正確模組化、正確參數化。

請正確指出你 Code Review 的項目，例如：

- 檢查 install - 符合動態版本更新，透過 $java_version 變數可正確引入不同版本進行安裝
- 檢查 service - 相依性  A -> B -> C 順序正確，使用 unless / onlyif 處理。

**Comment by hillhuang0552** [comment]
1.建議 PID 可以建立 pid 目錄放置 , 因不確認 /opt/karaf/ 下是程式還是其他的檔案

**Comment by edison0513** [comment]
install - 符合動態版本更新，karaf java可正確引入不同版本進行安裝
config - 依實際安裝，於公司環境不對外的狀態 install karaf feature 沒有透過maven掛proxy應該無法安裝
init - 使用-> ~>順序無誤

**Comment by abelyang999** [comment]
1. Proxy setting 測試 OK.
2. Install 4.2.0 再裝 4.1.5 會有 overwrite 和 dependence 問題, 建議在解 tar 前可以 rm -rf  ${corp104_karaf::install_path}/ 避免問題.
3. 同(2) 或可考量不同版本裝在不同  install_path 目錄,以 softlink 方式指向 ${corp104_karaf::install_path} ,如同一般 JDK 中 JAVA_HOME 之常見作法.
4. 從 apache site 下載了 sha512sum sig, 和 tarball 包的 sha512sum 的 sig 似未實際進行比對判斷後再安裝.

**Comment by shazi7804** [comment]
@hillhuang0552、@edison0513 OKAY

@abelyang999 
> 2.1 從 4.1.5 再裝 4.2.0 會有大量警告訊息,唯不知對軟體運作是否會造成影響.

疑 ? 有大量警告訊息，這應該不 work ? review code 應該要能指出問題，模擬兩可的答案會讓 PR 的人不知是否正確。

我們的角色是 Puppet module 的把關者，應要能提出建議、指正錯誤，然後最後決定是否 Merge。


請 @genchilu 參考其他 SE 的建議，有問題我們可以再討論。

**Comment by abelyang999** [comment]
@shazi7804 好的, 了解
因沒有檢查該目錄狀態,會發生 JAR HELL (classpath 帶進了2個版號的 jar 檔)情況,  如下粗黑體說明:
root      4923  0.0  0.0  17908  1968 ?        Sl   09:49   0:00 /opt/karaf/bin/karaf-wrapper /opt/karaf/etc/karaf-wrapper.conf wrapper.syslog.ident=karaf wrapper.pidfile=/opt/karaf/karaf.wrapper.pid wrapper.daemonize=TRUE wrapper.lockfile=/var/lock/subsys/karaf
root      4925  9.5  4.8 2453340 98868 ?       Sl   09:49   0:02  \_ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dkaraf.home=/opt/karaf -Dkaraf.base=/opt/karaf -Dkaraf.data=/opt/karaf/data -Dkaraf.etc=/opt/karaf/etc -Dcom.sun.management.jmxremote -Dkaraf.startLocalConsole=false -Dkaraf.startRemoteShell=true -Djava.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed:/usr/lib/jvm/java-8-openjdk-amd64/lib/endorsed:/opt/karaf/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/lib/jvm/java-8-openjdk-amd64/lib/ext:/opt/karaf/lib/ext -Djava.io.tmpdir=/opt/ka af/data/tmp -Xmx512m -Djava.library.path=/opt/karaf/lib/wrapper/ **-classpath /opt/karaf/lib/boot/org.apache.karaf.diagnostic.boot-4.1.5.jar**:/opt/karaf/lib/boot/org.osgi.core-6.0.0.jar:/opt/karaf/lib/boot/org.apache.karaf.main-4.2.0.jar:/opt karaf/lib/boot/**org.apache.karaf.jaas.boot-4.1.5.ja**r:/opt/karaf/lib/boot/org.apache.karaf.jaas.boot-4.2.0.jar:/opt/karaf/lib/boot/jna-4.5.0.jar:**/opt/karaf/lib/boot/org.apache.karaf.main-4.1.5.jar**:/opt/karaf/lib/boot/org.apache.karaf.diagnostic.boot-4.2.0.jar:/opt/karaf/lib/boot/jna-platform-4.5.0.jar:/opt/karaf/lib/boot/org.apache.karaf.specs.activator-4.2.0.jar:/opt/karaf/lib/wrapper/karaf-wrapper-main.jar:/opt/karaf/lib/wrapper/karaf-wrapper.jar -Dwrapper.key=TK4gRBrRkmIdWN5K -Dwrapper.port=32000 -Dwrapper.jvm.port.min=31000 -Dwrapper.jvm.port.max=31999 -Dwrapper.pid=4923 -Dwrapper.version=3.2.3 -Dwrapper.native_library=wrapper -Dwrapper.service=TRUE -Dwrapper.cpu.timeout=10 -Dwrapper.jvmid=1 org.apache.karaf.wrapper.internal.service.Main

**Comment by genchilu** [comment]
由於 karaf 是個要文件沒文件，要社群沒社群的工具，AC-TEAM 預計遲早要替換掉 karaf。
目前這個 module 我把他的 scope 定義為在 AC-TEAM 淘汰掉 karaf 前，先有個堪用的 module 幫我們管 AC-API 的 infra，省下日常維運更新設定檔，新增備援機的人工作業時間，在這個前提下：

1. @hillhuang0552 回復的pid 問題：karaf 預設 pid file 就會放在 karaf 目錄下面 (以我們公司情境會是 /opt/karaf)，我很快瞄文件沒看到怎麼設定，所以暫時不動。
2. @abelyang999 回復的 karaf 版本更新問題，之所以沒用目錄做區別版本有兩個原因：
   * 如一開始描述的我們不打算在 karaf 投資太多時間讓他更完善
   * 我更喜歡用 immutable server 的概念玩 infra as code (單純個人喜好) 。也就是說如果今天真的有需要升級 karaf 需求，直接拿一台新 VM 跑 puppet agent 裝新版 karaf 起來，並加到 A10 網域，在汰換掉舊版。

**Comment by shazi7804** [comment]
Okay
